# Generated by Django 5.1.2 on 2025-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_memorialpage_user_memorialpagesettings_photo_tribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='memorials/')),
            ],
        ),
    ]
